version: '3'
services:
  web:
    build: .
    volumes:
      - .:/home/python/app
    depends_on:
      - db
  db:
    image: mysql:8.0.34
    environment:
      MYSQL_ROOT_PASSWORD: mysecretpassword
      MYSQL_DATABASE: hospitaldatabase
      MYSQL_USER: root
      MYSQL_PASSWORD: root123
    volumes:
      - mysql-data:/var/lib/mysql
volumes:
  mysql-data:
